// User Search
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const CLEAR_USERS = 'CLEAR_USERS';

// Post Tweet
export const POST_TWEET_REQUEST = 'POST_TWEET_REQUEST';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_ERROR = 'FETCH_USERS_ERROR';
